"""Message input provenance.

Tags an :class:`~bus.events.InboundMessage` with its origin kind so that
downstream components (agent loop, hooks, multi-agent router) can apply
differentiated processing depending on *who* injected the message.

Origin kinds
~~~~~~~~~~~~
* ``external_user``   -- a real user sent the message via a channel.
* ``inter_session``   -- injected by another agent session (multi-agent relay).
* ``internal_system`` -- generated by the system itself (e.g. cron job trigger,
  heartbeat, startup probe).

Inspired by OpenClaw's ``sessions/input-provenance.ts``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Any, Literal, Optional

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

InputProvenanceKind = Literal["external_user", "inter_session", "internal_system"]

_VALID_KINDS = frozenset(("external_user", "inter_session", "internal_system"))


@dataclass
class InputProvenance:
    """Structured origin metadata attached to an inbound message."""

    kind: InputProvenanceKind

    # Optional routing context — populated for inter_session / internal_system
    origin_session_id: Optional[str] = None
    """Session ID of the originating session (for inter_session provenance)."""

    source_session_key: Optional[str] = None
    """Session key of the source session."""

    source_channel: Optional[str] = None
    """Channel the source session was talking on."""

    source_tool: Optional[str] = None
    """Name of the tool that triggered this injection (for internal_system)."""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _norm_str(value: object) -> Optional[str]:
    if not isinstance(value, str):
        return None
    trimmed = value.strip()
    return trimmed if trimmed else None


def normalize_input_provenance(value: object) -> Optional[InputProvenance]:
    """Parse a raw dict into :class:`InputProvenance`, or return ``None``."""
    if not isinstance(value, dict):
        return None
    kind = value.get("kind")
    if kind not in _VALID_KINDS:
        return None
    return InputProvenance(
        kind=kind,  # type: ignore[arg-type]
        origin_session_id=_norm_str(value.get("origin_session_id")),
        source_session_key=_norm_str(value.get("source_session_key")),
        source_channel=_norm_str(value.get("source_channel")),
        source_tool=_norm_str(value.get("source_tool")),
    )


def is_inter_session_provenance(provenance: Optional[InputProvenance]) -> bool:
    """Return ``True`` when *provenance* indicates an inter-session origin."""
    return provenance is not None and provenance.kind == "inter_session"


def is_internal_system_provenance(provenance: Optional[InputProvenance]) -> bool:
    """Return ``True`` when *provenance* indicates an internal system trigger."""
    return provenance is not None and provenance.kind == "internal_system"


def make_cron_provenance(source_tool: Optional[str] = "cron") -> InputProvenance:
    """Convenience factory for cron-triggered (internal_system) messages."""
    return InputProvenance(kind="internal_system", source_tool=source_tool)


def make_inter_session_provenance(
    origin_session_id: Optional[str] = None,
    source_session_key: Optional[str] = None,
    source_channel: Optional[str] = None,
) -> InputProvenance:
    """Convenience factory for cross-session relay messages."""
    return InputProvenance(
        kind="inter_session",
        origin_session_id=origin_session_id,
        source_session_key=source_session_key,
        source_channel=source_channel,
    )
